name: Bump dependencies
on:
  workflow_call:
    inputs:
      bump-branch:
        type: string
        default: bump
      commit-message:
        type: string
        default: "Bump dependencies"
      title:
        type: string
        default: "Bump dependencies"
      body:
        type: string
        default: |
          Bumping dependencies via GitHub Actions.

          If this does not build, then get the `bump` branch locally and fix the issues and then push back to GitHub.

          You can then merge the PR when it builds successfully.
      node-version-file:
        type: string
        default: ""
        description: "Node.js version file to determine the version to install"
      require-minimum-release-age:
        type: boolean
        default: true
        description: "Require pnpm-workspace.yaml to contain minimumReleaseAge before proceeding"
    secrets:
      GH_TOKEN:
        description: "GitHub token to create the PR, this will need to be set so that any PR checks are run. If not set, the default GITHUB_TOKEN will be used which will need permissions to write contents and pull-requests."
        required: false
      NPM_TOKEN:
        description: "NPM token to authenticate to a private package registry"
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deps-bump:
    name: Bump dependencies
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Bump dependencies
        uses: ../../bump
        with:
          bump-branch: ${{ inputs.bump-branch }}
          commit-message: ${{ inputs.commit-message }}
          title: ${{ inputs.title }}
          body: ${{ inputs.body }}
          node-version-file: ${{ inputs.node-version-file }}
          require-minimum-release-age: ${{ inputs.require-minimum-release-age }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
