name: Format

on:
  workflow_call:
    inputs:
      commit-message:
        type: string
        default: "Format all files correctly"
      branch:
        type: string
        default: ${{ github.head_ref }}
      command:
        type: string
        default: "format"
      turbo-cache:
        type: boolean
        default: false
      node-version-file:
        type: string
        default: ""
        description: "Node.js version file to determine the version to install"
    secrets:
      NPM_TOKEN:
        description: "NPM token to authenticate to a private package registry"
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Format code
        uses: ../../format
        with:
          commit-message: ${{ inputs.commit-message }}
          branch: ${{ inputs.branch }}
          command: ${{ inputs.command }}
          turbo-cache: ${{ inputs.turbo-cache }}
          node-version-file: ${{ inputs.node-version-file }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
