name: Format

on:
  workflow_call:
    inputs:
      commit-message:
        type: string
        default: "Format all files correctly"
      branch:
        type: string
        default: ${{ github.head_ref }}
      command:
        type: string
        default: "format"
      turbo-cache:
        type: boolean
        default: false
      node-version-file:
        type: string
        default: ""
        description: "Node.js version file to determine the version to install"
    secrets:
      NPM_TOKEN:
        description: "NPM token to authenticate to a private package registry"
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: ${{ inputs.node-version-file }}

      - name: Turbo Cache
        if: ${{ inputs.turbo-cache }}
        id: turbo-cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-

      - name: Install dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm install --frozen-lockfile

      - name: Format code
        run: pnpm run ${{ inputs.command }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: ${{ inputs.commit-message }}
          branch: ${{ inputs.branch }}
